spring:
  datasource:
    url: jdbc:mysql://47.106.128.36:3306/guotu
    username: root
    password: xiong123456
    driver-class-name: com.mysql.jdbc.Driver


server:
  port: 8090
  tomcat:
    uri-encoding: utf-8
  servlet:
    session:
      timeout: 10

